name: Publish Docker image

on:
  push:
    branches: [ production ]

jobs:
  publish_to_registry:
    runs-on: ubuntu-latest
    needs: [build_and_qa]
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: eddieantonio
        password: ${{ secrets.CR_PAT }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        tags: |
          ghcr.io/ualbertaaltlab/hello.altlab.dev:latest
