name: Publish Docker image

on:
  push:
    branches: [ production ]


jobs:

  build_and_qa:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Create requirements.txt (for Dockerfile)
      run: make requirements.txt
    - name: Upload requirements.txt
      uses: actions/upload-artifact@v2
      with:
        name: requirements.txt
        path: requirements.txt

    - name: tests
      run: |
        echo "ToDo : add test"


  publish_to_registry:
    runs-on: ubuntu-latest
    needs: [build_and_qa]
    steps:
    - uses: actions/checkout@v2

    - name: Test github.actor(for Dockerfile)
      run: echo "${{ github.actor }}"

    - name: Download artifact
      uses: actions/download-artifact@master
      with:
        name: requirements.txt



    - name: Build and push Docker images
      uses: docker/build-push-action@v2.0.1


      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ualbertaaltlab/hello.altlab.dev/hellotest
        # ALWAYS replace the latest tag!
        tags: latest


