name: Publish Docker image

on:
  push:
    branches: [ production ]


jobs:
  build_and_qa:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with mypy/black
      run: |
        # Typecheck
        poetry run mypy .
        # Lint
        poetry run black --check . --diff --exclude 'migrations/'


  publish_to_registry:
    runs-on: ubuntu-latest
    needs: [build_and_qa]
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ualbertaaltlab/hello.altlab.dev/hellotest
        # ALWAYS replace the latest tag!
        tags: latest